import os
import yaml
import json
from pathlib import Path
from datetime import datetime

# Relative paths assuming execution from root or script location
# Adjust as needed. This script assumes it runs from the project root or can find it.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent
SKILLS_DIR = BASE_DIR / "skills"
MEMORY_FILE = SKILLS_DIR / "99-common-utils/project-memory/memory-store/global_context.yaml"
REGISTRY_FILE = SKILLS_DIR / "00-master-architect/registry.yaml"
OUTPUT_FILE = BASE_DIR / "PROJECT_STATUS.md"

def load_yaml(path):
    if not path.exists():
        return {}
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def count_specialists(group_path):
    specialists_dir = group_path / "specialists"
    if not specialists_dir.exists():
        return 0
    # Count directories that have a SKILL.md
    count = 0
    for item in specialists_dir.iterdir():
        if item.is_dir():
            count += 1
    return count

def check_core_component(group_path, component_name):
    # component_name: 'orchestrator' or 'communicator'
    comp_path = group_path / component_name / "SKILL.md"
    return "✅" if comp_path.exists() else "❌"

def generate_markdown(context, registry, stats):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    phase = context.get('active_phase', {})
    
    md = f"""# 📊 Project Status Dashboard
**Generated:** {now}
**Project Version:** {context.get('project_info', {}).get('version', 'N/A')}

## 🚩 General Status
*   **Current Phase:** {phase.get('current', 'Unknown')}
*   **Milestone:** {phase.get('milestone', 'Unknown')}
*   **Status:** {phase.get('status', 'Unknown')}

## 🧩 Metrics by Skill Group (Cells)

| Group | ID | Orchestrator | Communicator | Specialists |
|-------|----|--------------|--------------|-------------|
"""
    
    total_skills = 0
    
    for group in registry.get('skill_groups', []):
        gid = group['id']
        name = group['name']
        folder_name = f"{gid}-{name.lower().replace(' ', '-').replace('/', '-')}"
        
        # Attempt to find the real folder (name might vary slightly)
        # Simple search by ID prefix
        found_dir = None
        for item in SKILLS_DIR.iterdir():
            if item.is_dir() and item.name.startswith(gid):
                found_dir = item
                break
        
        if found_dir:
            orch = check_core_component(found_dir, "orchestrator")
            comm = check_core_component(found_dir, "communicator")
            count = count_specialists(found_dir)
            total_skills += count
            md += f"| {name} | `{gid}` | {orch} | {comm} | **{count}** |\n"
        else:
            md += f"| {name} | `{gid}` | ⚠️ Missing | ⚠️ Missing | 0 |\n"

    md += f"""
**Total Migrated Specialists:** {total_skills}

## 📝 Recent Decisions
"""
    decisions = context.get('decisions_log', [])
    if not decisions:
        md += "*No decisions recorded yet.*\n"
    else:
        for d in decisions[-5:]: # Last 5
            md += f"* **{d['date']}**: {d['title']} ({d['status']})\n"

    md += """
---
*This report was automatically generated by the `status-reporter` skill.*
"""
    return md

def main():
    print(f"Generating report in: {BASE_DIR}")
    
    context = load_yaml(MEMORY_FILE)
    registry = load_yaml(REGISTRY_FILE)
    
    if not context or not registry:
        print("Error: Could not load context or registry files.")
        return

    markdown_content = generate_markdown(context, registry, {})
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    print(f"Report successfully generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
